### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Icefoxzhx** [happyte/2048#1]
Couldn't run on win10.
After I press downward key on keyboard, Error reports as follow:

> Traceback (most recent call last):
>   File "box.py", line 226, in <module>
>     main()
>   File "box.py", line 217, in main
>     matrix,score = actionObject.handleData()                     #处理数据
>   File "box.py", line 102, in handleData
>     newmatrix = self.toSequence(matrix)
>   File "box.py", line 71, in toSequence
>     GameInit.initData(Size,matrix,self.zerolist)
>   File "box.py", line 143, in initData
>     if matrix == None:
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by JAYqq** [comment]
Same problem in mac
